name: text_extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - opencv
  - tesseract
  - numpy
  - pdf2image
  - scikit-image
  - matplotlib
  - pillow
  - tesserocr
  - libarchive
  - pip:
    - deskew
